all: main00 main01 main02

main00: c00_main.c
	gcc -Wall -Wextra -Werror -o main00 c00_main.c

main01: c01_main.c
	gcc -Wall -Wextra -Werror -o main01 c01_main.c

main02: c01_main.c
	gcc -Wall -Wextra -Werror -o main02 c02_main.c
