all: main00 main01 main02 main03 main04 main05

main00: c00_main.c
	gcc -Wall -Wextra -Werror -o main00 c00_main.c

main01: c01_main.c
	gcc -Wall -Wextra -Werror -o main01 c01_main.c

main02: c02_main.c
	gcc -Wall -Wextra -Werror -o main02 c02_main.c

main03: c03_main.c
	gcc -Wall -Wextra -Werror -o main03 c03_main.c

main04: c04_main.c
	gcc -Wall -Wextra -Werror -o main04 c04_main.c

main05: c04_main.c
	gcc -Wall -Wextra -Werror -o main05 c05_main.c

